name: Deploy

on:
  page_build:
    release:
      types:
        - created
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      DIGITALOCEAN_APP_ID: ${{ secrets.DIGITALOCEAN_APP_ID }}
      VERCEL_HOOK_DEPLOY: ${{ secrets.VERCEL_HOOK_DEPLOY }}
    steps:
      - name: Trigger API Deployment
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
          "https://api.digitalocean.com/v2/apps/$DIGITALOCEAN_APP_ID/deployments"

      - name: Trigger Frontend Deployment
        run: curl -X POST $VERCEL_HOOK_DEPLOY
